// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configurações do Firebase para o projeto "u-connect-321e7"
  // Service Account: gpswox@u-connect-app.iam.gserviceaccount.com
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBu_gh30RGJEcZaYc3sli5JyzYW28hFXJ8",
    appId: "1:434891985510:web:111301663926374755888",
    messagingSenderId: "434891985510",
    projectId: "u-connect-321e7",
    authDomain: "u-connect-321e7.firebaseapp.com",
    storageBucket: "u-connect-321e7.firebasestorage.app",
    measurementId: "G-XXXXXXXXXX", // Atualizar com o Measurement ID do Firebase Console se necessário
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBu_gh30RGJEcZaYc3sli5JyzYW28hFXJ8",
    appId: "1:434891985510:android:5638d91b3faf20ba84d3a7",
    messagingSenderId: "434891985510",
    projectId: "u-connect-321e7",
    storageBucket: "u-connect-321e7.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCUzr3FldnBECIpEDpk3xmjXS8Rh4AAbI8",
    appId: "1:434891985510:ios:9a2d8c20c239480884d3a7",
    messagingSenderId: "434891985510",
    projectId: "u-connect-321e7",
    storageBucket: "u-connect-321e7.firebasestorage.app",
    iosBundleId: "com.uconnect.app",
  );
}
